- XIVComboExpanded/Combos/MNK.cs
Just quickly adds a level check to fix the Perfect Balance Feature when synced, as reported in #87.
> Perfect Balance Feature Fix

- XIVComboExpanded/Combos/NIN.cs
- XIVComboExpanded/CustomComboPreset.cs
Added an option similar to Hurajin's functionality, but using the base Ninjitsu skill. This allows you to spam the skill without accidently using a GCD on hurajin once your Raiju stacks are consumed.
Found it covered a use case where the same button that performs a Raiton does the Raiju "combo" follow up, but doesn't require chaining Hurajin -> Ninjitsu and Hurajin -> Raiju.
> [NIN] Ninjitu to Fleeting/Forked Raiju

- XIVComboExpanded/Combos/NIN.cs
- XIVComboExpanded/CustomComboPreset.cs
Adds a feature to replace Aeolian Edge with Armor Crush when Huton is less than equal to 40 seconds, and Huraijin when Huton is inactive.
> [NIN] Aeolian Edge / Huton Feature

- XIVComboExpanded/Combos/MNK.cs
- Updated Monk AoE combo to use the Lunar sequence (3 of the same) for Tornado Kick/Phantom Rush, because it doesn't require 3 unique Beast Chakra.
- Removed the redundant Lunar Nadi conditional expression, since the prior Solar conditional is terminating.
> Monk AoE combo update

- XIVComboExpanded/Combos/RPR.cs
- Fixed bug where Communio would be skipped if the player was behind on using Lemure's Slice/Scythe.
**Context:** Currently, if the player has 1 Shroud Orb remaining, but >0 Void Orbs remaining (ie. they forgot to use Lemure's Slice), and do _not_ have the relevant 'X Lemure's Feature' active to automatically integrate Lemure's attacks, if they hit the button that would otherwise turn into Communio (whether that's the Slice combo, the Scythe combo, Soul Slice, Shadow of Death, or Gibbet/Gallows/Guillotine directly), it will instead simply cast Void Reaping or Cross Reaping, whichever is empowered (or Grim Reaping, if it's the AoE version), using the last Shroud Orb and ending Enshroud _without_ casting Communio.
Since failing to cast Communio is even more of a loss than simply missing the …
> [BUGFIX] Use Communio on last Shroud orb even if Void orbs remain

- XIVComboExpanded/Combos/NIN.cs
For the aeolian edge combo replacement options, if both mudra and raiju ready are up prioritize mudra ability. This is because you can store multiple raiju ready stacks (up to 3), but using fleeting raiju when you're in the middle of a mudra breaks the mudra.
> NIN aeolian edge mudra/raiju ready tweak

- XIVComboExpanded/Combos/ADV.cs
- XIVComboExpanded/CustomComboPreset.cs
All BLU spells are lvl 1 so, I don't think there is a need to check it's level.
> add BLU rez spell Angel Whisper to swift raise feature

- XIVComboExpanded/Combos/NIN.cs
- XIVComboExpanded/CustomComboPreset.cs
A common opener is to Huton into Hide, so putting them onto the same button is ergonomic. Hide and Ninjutsu are also mutually exclusive actions, with Hide activating bunnies if under Mudras.
> Ninja replace Hide with Ninjutsu

- XIVComboExpanded/Combos/WAR.cs
Using Storm's Eye while there's between 20-30s of Surging Tempest remaining could lead to overcap if Inner Release is used soon afterwards. This PR modifies Storm's Eye usage criteria such that it would only be selected if Surging Tempest wouldn't be overcapped even if IR is used as soon as it comes off of cooldown.
> WAR: Avoid using Storms Eye if IR would overcap Surging Tempest

- XIVComboExpanded/Combos/WAR.cs
Storm's Eye may be unavailable during down level content
> WAR: Do not upgrade StormsPath to StormsEye when downleveled

- XIVComboExpanded/Combos/BLM.cs
Sharpcast gets 2 charges at level 88, it's considered on cooldown while a single charge has been used. It should always be prioritized to buff the next thunder cast.
> BLM: Support multi-charges sharpcast

- XIVComboExpanded/Combos/AST.cs
- XIVComboExpanded/CustomComboPreset.cs
- Added a new combo, `Play to Redraw`, which replaces Play with Redraw if a card is drawn and is a seal the player already has.
- Removed the combos and code around Crown Play, since it was removed and merged into Major Arcane in 6.3, and thus no longer functions at all.
- Updated the `Play to Draw to Astrodyne` feature so it will also defer to Astrodyne if Draw is off cooldown, but a card is already drawn.
Edit: Resolves #181
> [FEATURE] Astrologian Play -> Redraw feature

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/CustomComboPreset.cs
- If the Royal Authority Divine Might Feature is enabled, Holy Spirit will be cast preferentially over Atonment and the rest of the combo chain during the Fight or Flight buff, due to the increased potency.
- Same principle applies if Prominence Divine Might Feature is enabled, Holy Circle is prioritized during FoF.
- FoF is only replaced with Goring Blade if Goring Blade is off cooldown.  This just makes the button revert back to FoF after Goring Blade is used, rather than only once FoF fades.
- If both the Requiescat FoF feature and the FoF Goring Blade feature are enabled, Goring Blade is also placed on the Requiescat button during the buff.
- Goring Blade is used preferentially over the Confiteor combo, because despite doing less potency than Confiteor, Goring Blade requires melee …
> [FEATURE] Paladin Requiescat refinement

- XIVComboExpanded/Combos/PLD.cs
- Added in check for FoF and Req cooldowns to Goring Blade insertion to the combo.
- This fixes a bug where Req will swap to Goring Blade even before FoF and Req are used.
Edit:
- Also fixed bug with Requiescat + FoF feature preventing FoF from being used.
> [BUGFIX] PLD Requiescat + Goring Blade

- XIVComboExpanded/Combos/SMN.cs
- XIVComboExpanded/CustomComboPreset.cs
Change Summon Demi into Summon Carbuncle when pet is absent. This is similar to RadiantCarbundleFeature, but since Summon Demi is used in the opener and rotation, it's easier to notice when pet is missing and more intuitive to react with than Radiant Aegis, which is used on demand. Summon Demi (and variants) cannot be used without Carbuncle already summoned.
> SMN: Summon Demi into Carbuncle when absent

- XIVComboExpanded/Combos/MNK.cs
- XIVComboExpanded/CustomComboPreset.cs
Similar to the existing Twin Snakes / True Strike feature, but instead replaces True Strike instead. Toggling this feature on but leaving the other feature off allows you to put both skills on the bar, with True Strike conditionally changes to Twin Snakes, but Twin Snakes stays as Twin Snakes unconditionally. This allows you to force a buff refresh before entering a burst window.
> Monk True Strike -> Twin Snakes feature

- XIVComboExpanded/Combos/AST.cs
- The Draw/Redraw feature only tries to use Redraw if the buff needed to use Redraw is present.
- Removed the no-longer-used buffs for Lord and Lady of Crowns, since that behavior was rolled into the base game in 6.1.
> [BUGFIX] Redraw only with Clarifying Draw

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Similar to Transpose->Umbral Soul, but in reverse. This allows the unmodded Transpose to be used to to enter Astral Fire for [rotation optimization](https://www.thebalanceffxiv.com/jobs/casters/black-mage/advanced-guide/).
> BLM: Umbral Soul into Transpose

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Since Paradox can still be cast using Fire spells, this gives more flexibility to rotation by allowing the player to renew Enochian at a reduced cast time using Blizzard compared to casting the Fire-aspected Paradox.
> BLM: Option to change Blizzard into Paradox only during Umbral Ice

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
When Thunder is procced and Sharpcast is active but still has another charge remaining, it's easy to double tap the key bound to Thunder with the intention of queuing the spell but instead casting Thunder and accidentally also use up the second Sharpcast charge as well. This is usually undesirable because it often leads to the Sharpcast buff expiring before it is actually needed.
This change adds an option to defer changing Thunder into Sharpcast until the GCD window for Thunder has elapsed.
> BLM: Option to delay Thunder->Sharpcast to avoid accidental usage

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
The standard AoE rotation is: `(Umbral Ice) Fire2 -> Fire2 -> Fire2 -> Flare -> Flare`
But the BlackFire2 combo causes the rotation to be: `(Umbral Ice) Fire2 -> Fire2 -> Flare -> Flare`
This is because the Fire2 cast during Astral Fire (i.e. second Fire2) grants Enhanced Flare while dropping the number of Umbral Hearts to 2. The `UmbralHearts == 1` condition never matches because of Enhanced Flare is active.
This change also adds a new option to modify the rotation when Triplecast is used so that the Flares are made instant cast.
> BLM: Fix Fire2 rotation and support Triplecast rotation

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Fixes bug in option toggle for Thunder/Sharpcast delay causing the original feature to be disabled when the new option has not been enabled.
> BLM: Fix Thunder/Sharpcast delay option toggle

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/IconReplacer.cs
Both single target and AoE GCD rotations include a spell that costs MP to cast. When out of mana (e.g. from casting clemency), the GCD combos becomes "stuck" on the spell icon because there's not enough mana for it to be cast.
This change skips the spell in the rotation when there's not enough mana to cast it. The "Divine Might" proc would be overwritten by the next GCD attack and would be wasted. But that is better than not being able to use any GCD until mana has regenerated.
> PLD: Skip spell in GCD combo when no mp

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/CustomComboPreset.cs
The existing combo forces Divine Might proc to be used up during Fight or Flight window to maximize dps. But often the proc is useful to be saved for movement. It is currently not possible to save the proc for later.
This change splits out Holy Spirit usage during FoF to a separate option. This is a new option that will initially be disabled so the behavior of the original combo will be affected. Holy Spirit can still be casted manually during FoF using a dedicated key. I think it's a more deliberate playstyle that should be encouraged as the default. Anyone who has been using the original feature and is obsessed with maximizing dps would probably notice the change and discover the new option pretty quickly.
> PLD: Split RoyalAuthority combo FoF behavior to a separate option

- XIVComboExpanded/Combos/PLD.cs
Divine Might is available at level 64 but but Holy Circle is level 72. In a level 70 dungeon, the AoE combo can get stuck on Holy Circle if the Divine Might buff is first acquired using the single-target combo, followed by activating Fight or Flight, then using the AoE combo.
The single-target combo doesn't have this issue because Holy Spirit is a level 64 spell, so it is always available when the Divine Might buff is active. I added level requirement to the Holy Spirit condition just to make it consistent with Holy Circle.
> Fix Paladin Prominence combo stuck on Holy Circle when downleveled

- XIVComboExpanded/Combos/PLD.cs
When all the Requiescat features have been toggled on to turn Requiescat into a one-button combo of [FoF -> Requiescat -> Goring Blade -> Confiteor -> ...], downleveling causes the combo to be stuck on Requiescat with it being unusable.
This change keeps the icon to be FoF in during downlevel so that FoF cooldown can be tracked via the icon.
> PLD: Show FoF cooldown on Requiescat combo when downleveled

- XIVComboExpanded/Combos/WAR.cs
- Implemented handling for Primal Ruination and Primal Wrath for WAR.
- Primal Wrath is currently prioritized over Primal Ruination if both are available, since it is an oGCD.
Fixes #257
> [FEATURE] WAR - Primal Ruination and Primal Wrath

- XIVComboExpanded/Combos/RDM.cs
- XIVComboExpanded/CustomComboPreset.cs
- Added support for Grand Impact.
- By default, Grand Impact will be prioritized over Veraero/Verthunder, and will always be prioritized over Verstone/Verfire.
- Added a combo to prioritize Veraero/Verthunder over Grand Impact, if the user wishes.
- Added a combo to add Grand Impact to Acceleration when available.
- Fixed the inaccurate reference to Scorch in the RedMageVerprocFeature description.
- Also added the spell ID, level, and relevant buff for the other two DT abilities, Prefulgence and Vice of Thorns.  No combos implemented for either yet, though.
Fixed #259
> [FEATURE] RDM - Grand Impact support

- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/CustomComboPreset.cs
Replace Shinten with Zanshin while under the effect of Zanshin Ready.
Confirmed the action ID for Zanshin using ReAction.
> [FEATURE] SAM - Zanshin Support

- XIVComboExpanded/Combos/RPR.cs
This does not change functionality of any current combos, just allows them to work after level 96.
> RPR: bugfix for gluttony's executioner gibblet/gallows/guillotine.

- XIVComboExpanded/Combos/MCH.cs
Fix Excavator not showing in Hot Shot (Air Anchor) / Drill / Chainsaw Feature.
> Fix MCH Excavator

- XIVComboExpanded/Combos/DOL.cs
- XIVComboExpanded/CustomComboPreset.cs
This is my first foray into Dalamud plugin dev, but this change was straightforward enough! **Rest** is an invaluable new FSH skill that lets you quit a cast without quitting fishing altogether. **Cast** is definitely the best replacement target, despite the existing Hook replace feature.
Tested in-game, works like a charm.
> New feature: Replace Cast with Rest when fishing

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/Combos/SMN.cs
- [PLD] Fixed the FoF Goring Blade combo when used with Requiescat FoF combo.
- [SMN] Fixed the Gems Enkindle Feature.
- I'm not sure what changed about the gauge, but the `IsXAttuned` fields aren't working as they used to.  Swapped to `AttunmentTimerRemaining`.
- Fixes #285
Both are working with a local build.
> [BUGFIX] Gemshine + Enkindle and Requiescat + Goring

- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- Implemented combo that turns Lemure's Slice/Scythe into Sacrificium when less than 2 Void Shroud (ie Lemure's Slice and Scythe not usable).
- Implemented sub-combo to override this priority and always replace Lemure's Slice/Scythe with Sacrificium when it is available.
Tested and working locally.
Edit: Fixes #277, related to #276
> [FEATURE] Reaper Lemure's Slice -> Sacrificium

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Fixed wrong flare star ID (I think previous one was a Bozja action LOL)
Added despair -> flare star feature.
> BLM: bugfix flare star ID and added child feature to despair

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/CustomComboPreset.cs
- Removed the FoF Goring Blade feature, as it is now baseline.
- The prior check on Requiescat for including Goring Blade now depends on (and respects) the player's selection for whether FoF changes into Goring Blade in the base game.
- Implemented new features for including Goring Blade, when available, on Royal Authority and Prominence buttons.
- Implemented new features for including the Confiteor combo, when available, on Royal Authority and Prominence.
- Atonement usage outside of FoF is now delayed until it would be overwritten by Royal Authority, per current guidance in The Balance.
- It will also be used if it would otherwise expire
- During FoF, Atonement or Holy Spirit are now intelligently prioritized based on whether the higher-potency Sepulchre can be fit inside the remaining …
> [FEATURE] Paladin update/refactor

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/CooldownData.cs
- XIVComboExpanded/CustomCombo.cs
- Goring Blade being present on Requiescat no longer improperly requires the Requiescat Confiteor combo to also be active.
- IsCooldown now properly returns false for an ability where cooldownElapsed == 0 (which is what abilities off cooldown have it set at).
- CalcBestAction now properly returns the first action rather than the second if both have the exact same cooldown remaining.
> [BUGFIX] IsCooldown and Goring Blade

- XIVComboExpanded/Combos/VPR.cs
Noticed a nit here, if you're underleveled for this, it'll replace it unconditionally
> Add level check to FuryAndIre feature

- XIVComboExpanded/Combos/ADV.cs
- XIVComboExpanded/Combos/AST.cs
- XIVComboExpanded/Combos/BRD.cs
- XIVComboExpanded/Combos/DRG.cs
- XIVComboExpanded/Combos/DRK.cs
- XIVComboExpanded/Combos/GNB.cs
- XIVComboExpanded/Combos/MCH.cs
- XIVComboExpanded/Combos/PCT.cs
- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/Combos/RDM.cs
- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/Combos/SCH.cs
- XIVComboExpanded/Combos/SGE.cs
- XIVComboExpanded/Combos/SMN.cs
- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/Combos/WAR.cs
- XIVComboExpanded/CooldownData.cs
- XIVComboExpanded/CustomCombo.cs
- Revamped CooldownData, based on prior work by and with significant input from @vitharr137.
- Removed a number of not currently useful functions, which can be replicated by remaining functions anyway.
- Updated the mechanics of a number of the CooldownData functions.  Full change details can be found at:
- https://github.com/MKhayle/XIVComboExpanded/issues/305#issuecomment-2226556969
- Renamed `IsOffCooldown` to `IsCooldownUsable`, and clarified its semantics with regards to charge-based actions.
- Removed the global functions `HasCharges`, `HasNoCharges`, and `IsOnCooldown`.
- All prior usages of these have been replaced with `IsCooldownUsable`.
- Added new function `IsRecharging`, which returns whether an ability is below maximum charges, without regard to whether it is usable …
> [BUGFIX] CalcBestAction and CooldownData

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Extra naughty feature to facilitate mental math gymnastics for real-time comparison of Enochian timer to fire 4 cast time.
> BLM: Add enochian timer feature

- XIVComboExpanded/Combos/ADV.cs
- XIVComboExpanded/Combos/AST.cs
- XIVComboExpanded/Combos/BRD.cs
- XIVComboExpanded/Combos/DRG.cs
- XIVComboExpanded/Combos/DRK.cs
- XIVComboExpanded/Combos/GNB.cs
- XIVComboExpanded/Combos/MCH.cs
- XIVComboExpanded/Combos/PCT.cs
- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/Combos/RDM.cs
- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/Combos/SCH.cs
- XIVComboExpanded/Combos/SGE.cs
- XIVComboExpanded/Combos/SMN.cs
- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/Combos/WAR.cs
- XIVComboExpanded/CooldownData.cs
- XIVComboExpanded/CustomCombo.cs
- XIVComboExpanded/CustomComboPreset.cs
Alrighty, time to talk about secret combos:
This one adds a few combos:
1. Merge steel/dread fangs into 1 button like PvP (with selectable start move, otherwise weaves as expected)
2. Merge steel/dread maw into 1 button (same selectable start move as above)
3. Merge the Viper combos onto 1 button also like PvP
4. Same but for the Viper AoEs
> Add PvP style secret combos

- XIVComboExpanded/Combos/DNC.cs
- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- Implemented ST and AoE features to automatically replace the standard combo attacks with Saber Dance when at >= 85 Esprit.
- Implemented ST and AoE features to reduce this threshold to 50 when under Technical Step.
- Implemented feature to do the same with Dance of the Dawn when it is available and >= 50 Esprit.
- Adjusted Viper's AutoGenerationsLegaciesFeature to reference the level constants, use a bit more compact conditional.
Tested locally, except for the Dance of the Dawn feature, since my Dancer is only 90 atm.
Fixes #322
> [FEATURE] Automatic Saber Dance

- XIVComboExpanded/Combos/VPR.cs
- Updated the Twin Coil features so they no longer also include Uncoiled Twinfang and Uncoiled Twinblood.
- Fixed some incorrect addressing of Twinfang and Twinblood abilities for Hunter's Coil (which inadvertently prevented the bug on specifically that ability).
- Removed some unnecessary else statements, when the conditional preceding it is terminating (ie. `return`).
- Fixes #329.
> [BUGFIX] Uncoiled Fury Followup and Coils/Dens

- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- When either of the PvP Dread combos are selected, as well as one of the Twin Coil features, the oGCD followups to the Coil/Den actions are also now included.
- Also renamed the `Twin Coil AoE feature` to `Twin Den (AoE) Feature`, since "Coil" are the single target actions.
- Fixes #328.
> [FEATURE] PvP Dread combo + oGCDs

- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/CustomComboPreset.cs
- Re-implemented the Kyuten Shoha feature, using the new merged DT Shoha.
- Uses the same combo ID as previously, so it should auto-re-enable for anyone that had it selected previously.
- Implemented a Kyuten Zanshin feature to mirror the Shinten Zanshin feature.
> [FEATURE] Kyuten Shoha/Zanshin feature

- XIVComboExpanded/Combos/PCT.cs
Rainbow Drip is learned at level 92. If you enable `#145 Rainbow Drip Starter` while not being lv92 or higher, it still replaces Fire in Red, though you cannot use as is an action not learned. 
My PCT is 91 almost 92, but I assume will have same issue if you have it on while being sync'd
It should only replace if Picto is lv92 or higher.
> [BUG] PCT Rainbow Drip Starter below lv92

- XIVComboExpanded/Combos/BLM.cs
Based 7.01 changes for level synced content.
> BLM: update umbral soul level to 35

- XIVComboExpanded/Combos/PLD.cs
- Holy Spirit is now prioritized if Requiescat is active even if Fight or Flight is not
- This fixes an issue while leveling and below the level where the full Confiteor combo is acquired, where one or more stacks of Req may still be active after FoF ends.
Fixes #356
> [QUICKFIX] Paladin - Holy Spirit under Requiescat

- XIVComboExpanded/Combos/RPR.cs
Pre-communio, the buff from Enhanced Reaping persists after shroud, so need to ensure we're in shroud here
> Fix for pre-Communio ReaperSliceEnhancedEnshroudedFeature

- XIVComboExpanded/Combos/PLD.cs
- The spell ID for Imperator is now properly returned when FoF and Req are compared by cooldown.
Fixes #362
> [BUGFIX] Requiescat/Imperator upgrade

- XIVComboExpanded/Combos/DRG.cs
- Added action IDs, buff IDs, and levels for DRG 90-100.
- Updated the Stardiver Dragonfire Dive feature to also check for and include Rise of the Dragon
- Stardiver also includes and prioritizes Starcross when available.
Fixes #347 
I've tested the Rise of the Dragon feature, but my Dragoon is only 92, so I cannot test Starcross yet.
> [FEATURE] DRG - Level 92 and 100 actions

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
First pass on new combo presets; updated between the leylines features for retrace. Did not implement aoe accessibility combo yet. 
Let me know if the icons make sense:
> BLM: Update combo presets

- XIVComboExpanded/Combos/AST.cs
- Uses InCombat() so that astros don't start with combust (enables precasting for raid countdown timers)
- Arguably 1 ms faster for endgame since I reversed the order of Combusts 🤡
> Smol dot timer rewrite feature for Astrologian

- XIVComboExpanded/Combos/GNB.cs
- XIVComboExpanded/CustomComboPreset.cs
Ok, hear meow-t
I was thinking on what might make GNB more interesting, and landed on a VPR-style continuation thing for their continuation ability. It collapses a bunch of stuff onto continuation, like Burst Strike/Fated Circle, which kind of make sense to follow up their base abilities.
I marked it secret, since it does a fair amount of stuff, but wdyt?
(Also removed that Sonic Break/Bow Shock thing, since Sonic Break is now a followup to No Mercy, and that's how it works in this feature as well)
> [DRAFT] Remove non-working GNB combo, add new Continuation style combo

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/Combos/BRD.cs
- XIVComboExpanded/Combos/DNC.cs
- XIVComboExpanded/Combos/GNB.cs
- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/Combos/WAR.cs
- XIVComboExpanded/Combos/WHM.cs
- XIVComboExpanded/CustomComboPreset.cs
- Fixed bug with Bard Shadowbite feature and Barrage.
- Increased refresh buffer for Bard DoTs to 5s instead of 2.8s, since Bard is punished much more strongly for letting their DoTs drop.
- Split `(Between the [Retraced]) Ley Lines` into two combos, allowing the user to select whether they want the Retrace cooldown check.
- Updated a number of Dancer combo icon lists.
- Revise the Dancer Saber Dance features:
- Now uses a single base combo for automatic usage of Saber Dance in both AoE and single target
- Seperate (secret) ST and AoE combos to increase the auto-use threshold to 85 instead of 50.
- Sub-combo of the above to reduce the auto-use threshold back down to 50 during Technical Step.
- Sub-combo of the above to reduce the auto-use threshold back down to 50 for Dance of the Dawn.
- …
> [FEATURE] AttributesRework revisions/bugfixes/additions

- XIVComboExpanded/Combos/DRG.cs
- XIVComboExpanded/CustomComboPreset.cs
- Fixed bug in Dragoon Vorpal Thrust Option and Disembowel Option that prevented them from working
- Fixed bug causing both of the main Dragoon combo options to affect both buttons.
- Updated main single-target combo block structure.
- Pulled in Dragoon All-In-One combo from my local files, and included a header pending the Attributes Rework
- Pulled in a single target version of the AoE Wyrmwind Feature, also with a Rework header.
- Reworded the descriptions of the two Double combo features to clarify what they do.  Also swapped the var names to match the combo names.
- Renamed BarrageThrust to LanceBarrage and ExplosiveThrust to SpiralBlow, to match English client naming.
- Removed duplicate BarrageThrust2 and ExplosiveThrust2 definitions.
- Added buff and debuff definitions the new …
> [BUGFIX] Dragoon Combos

- XIVComboExpanded/Combos/BRD.cs
On BRD, Bloodletter changes to Heartbreak Shot at 92. For some reason, the replacer doesn't work properly if you drag Heartbreak Shot onto the bar, it registers as a different ID, same with returning Bloodletter
> Bugfix for BRD Bloodletter/HeartbreakShot

- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/CustomComboPreset.cs
I used the API documentation [here](https://dalamud.dev/api/Dalamud.Game.ClientState.JobGauge.Types/Classes/SAMGauge#hassetsu) for the job gauge info.
This sub-option is specifically to handle fast SAM's odd burst window, which looks like this:
We want to delay the Tsubame (6th icon) until after applying Higanbana (4th and 5th) icons. With the change in this request, we will not replace Iaijutsu with Tsubame while there is a single Sen active, allowing us to re-apply Higanbana first. Without this option, the existing behavior is that we are forced to use Tsubame first to clear the Tsubame-ready buff, which delays re-applying Higanbana.
Note, C# XOR is only functional for two operands, so I'm using a fairly cheap Linq query. I can expand this out to the actual logic operators if need be, …
> [FEATURE] SAM - Option to not replace Iaijutsu with a single Sen active

- XIVComboExpanded/Combos/GNB.cs
- XIVComboExpanded/CustomComboPreset.cs
Putting Gnashing Fang and Danger Zone on the same ST spender button felt intuitive for me, marked as accessibility
> Add a few extras to single target for GNB

- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- Implemented a new feature that checks for and replaces both Steel/Reaving Fangs/Maw with whichever of the 3rd combo hits is currently empowered.  Fixes #414.
> [FEATURE] Viper auto-select 3rd combo hit

- .editorconfig
- XIVComboExpanded/Combos/ADV.cs
- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/Combos/MCH.cs
- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/Combos/SGE.cs
- XIVComboExpanded/CustomCombo.cs
- XIVComboExpanded/CustomComboPreset.cs
- XIVComboExpanded/Interface/Changelog.cs
- Rewrote most of the existing Reaper combos
- Merged a number of separate single target and AoE combos.
- Merged a large number of combos that used to be separate per target button, but had the same effect
- Most of the Reaper combos now note that they also apply to any other features that cause their target action to be a replacement for something else.
- Example, turning Lemure's Slice into Sacrificium now also works when turning Gibbet/Void Reaping into Lemure's Slice.
- Both of which then also work when turning Nightmare Slice into Gibbet.
- Deleted the Sacrificium Priority combo, because it was a bear to code and strictly unneeded with the existing first and third weave options.
- Deleted the Soul Sow on Shadow of Death feature.  We already have options for Slice, Nightmare Scythe, …
> [FEATURE] Reaper revamp

- XIVComboExpanded/Combos/PCT.cs
- XIVComboExpanded/CustomComboPreset.cs
- Updated Starry Muse + Star Prism combo to no longer assume the Starry Muse + Motif combo is also taken.
- If the Muse + Prism combo is enabled and the Muse + Motif combo is not, then Prism will replace Scenic/Starry Muse, but not Landscape/Starry Sky Motif.
- If both are enabled, Prism will act as it currently does, replacing both the Muse and the Motif when available.
- Prioritized Prism over Starry Muse.  I don't THINK it's possible to have both available at once, but just in case.
- Renamed a number of the PCT globals to match their English client names, and sectioned the PCT action IDs by category/association.
- Updated the icon pattern and combo name for the Landscape Muse/Motif and Muse/Prism combos.
Fixes #461
> [FEATURE] Adjust Star Prism combo

- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- Added a new combo option to make it so the oGCD replacments on the Vice combo buttons only replace with one of the two Twin actions, rather than both of them in order.
- This also applies to Steel/Reaving Fang/Maw, if the `Steel Coil Feature` is selected.
- This is strictly overridden by the `Include All oGCDs` combo, as the documented behavior of that combo is to replace Fangs/Maws/Coils/Dens with *all* of the oGCDs.  If there's interest, may make a subfeature of this combo with similar behavior.
Fixes #440
> [FEATURE] VPR: Vice combo oGCD split

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/Combos/MNK.cs
- XIVComboExpanded/Combos/RPR.cs
- Fixed RPR level checks for Automatic Soul Reaper to use `>=` instead of `>`.
- For good measure, searched for every other usage of `>` on level and replaced with `>=`.
Fixes #469
> [QUICKFIX] Level checks greater-than-or-equal-to

- XIVComboExpanded/Combos/PCT.cs
- XIVComboExpanded/CustomComboPreset.cs
- Adds a feature to replace Holy in White with Hammer Brush and its combo chain when they are usable.  
- Named Holy Hammer Combo.
- Falls under the Holy Comet Combo parent group. 
- Does not have priority over the Rainbow Holy Combo.
- Edited the Rainbow Holy Combo description to clarify it has priority over this Holy Hammer Combo.
- My first pull request, please forgive any errors!
Addresses feature request #444
> PCT: Add Holy Hammer combo feature

- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/CustomComboPreset.cs
- Merged Mangetsu and Oka combos and implementation code.
- Added new combo that auto-selected Oka or Mangetsu based on which Sen is missing
- Added sub-combo to also auto-select them by remaining buff timer.
- Added sub-combo to also include Tenka/Tendo Goken, and Tsubame if selected, when both Sen are present.
- Added a number of missing levels and action IDs for SAM.
- Renamed the Jinpu and Shifu buff constants to match their in-game name since Endwalker.
Fixed #472
> [SAM] Auto-AoE

- XIVComboExpanded/Combos/SAM.cs
- XIVComboExpanded/CustomComboPreset.cs
Creates a new combo section "Guren".
Adds a feature in the Guren section to replace Hissatsu: Guren with Zanshin when it is available.
Adds a feature in the Guren section to replace Hissatsu: Guren with Shoha when Meditation is full.
Uses very similar code to that found in the Kyuten features.
Tested using v2.0.1.2 as a base version on a local drive, seems to work as intended.
Edited the SamuraiKyutenGurenFeature in CustomComboPreset.cs to fix a typo in the icons (it displayed HissatsuShinten when it should have displayed HissatsuKyuten).
I didn't edit anything in SAM.cs lines 180-186, 197-198, or 225-227.  I am not sure why it's flagging those lines as changed.  
Addresses #450
> [SAM] Add Hissatsu: Guren features

- XIVComboExpanded/Combos/SMN.cs
- XIVComboExpanded/CustomComboPreset.cs
- Implemented new feature that replaces each of the 3 elemental primal summons with their respective Astral Flow action when their Favor buff is active.
Fixes #446
> [FEATURE] [SMN] Primal Favor feature

- XIVComboExpanded/Combos/DNC.cs
- Merged the combo blocks for `DancerDanceStepCombo`, `DancerCombinedStandardStepTechnicalStep`, and `DancerLastDanceFeature` into the same block, to avoid the combos randomly failing if multiple are valid at the same time.
- Reordered that block so the dancing feature occurs before the Closed Position check, since you cannot use Closed Position while actively dancing.
Fixes #506
> [BUGFIX] Standard Step/Technical Step combo collision

- XIVComboExpanded/Combos/RDM.cs
- XIVComboExpanded/CustomComboPreset.cs
Fixes #494.
Ensures combo into Vice of Thorns and Prefulgence actions (in that order of priority) after Embolden and Manafication are used and the readying buff is applied. Also shows unreadied Prefulgence while stacks of Manafication have yet to be consumed to indicate that should be readied soon.
Manafication will now not replace Embolden while out of combat, as it cannot be cast outside of combat.
> [BUGFIX] RDM Embolden to Manafication skipping Prefulgence

- XIVComboExpanded/Combos/DNC.cs
Fixes #513
Looks like the bugfix from #507 accidentally made classic Last Dance Feature (3813) and expanded Partner Feature (3815) dependent on accessibility Dance Step Combo (3802) being enabled. They should now all be usable both independently or in conjunction as Kaedys intended.
> [BUGFIX] Last Dance Feature & Partner Feature disabled when Dance Step Combo not enabled.

- XIVComboExpanded/Combos/DNC.cs
Fixes bug reported in [this comment](https://github.com/MKhayle/XIVComboExpanded/pull/507#issuecomment-3201641431) on #507 
Adds Dance Step Combo (3802) enabled check for Technical Step replacement with next steps.
> [BUGFIX] DNC Dance Step Combo enabled for Technical Step even when disabled
