- XIVComboExpanded/Combos/NIN.cs
- XIVComboExpanded/CustomComboPreset.cs
A bit embarrassing I let that slip given I main Ninja.
> [NIN] Fix Huton feature for Endwalker duration

- XIVComboExpanded/Combos/BRD.cs
- Fixed Iron Jaws Feature conditional that was inappropriately referencing the Pre Iron Jaws Feature definition instead.
Fixes #120
> [Bugfix] Iron Jaws Feature

- XIVComboExpanded/Combos/DRG.cs
- XIVComboExpanded/CustomComboPreset.cs
All 3 buffs on the same button
> DRG: Lance Charge to Dragon Sight and Battle Litany

- XIVComboExpanded/CustomCombo.cs
- XIVComboExpanded/CustomComboCache.cs
- XIVComboExpanded/IconReplacer.cs
- XIVComboExpanded/Service.cs
- XIVComboExpanded/XIVComboExpanded.json
- XIVComboExpanded/XIVComboExpandedPlugin.cs
Tested rapidly as a Monk on the new trial and everythin seemed fine.
Something to take care of would be this change in **CustomCombo.cs:**
`protected static bool HasPetPresent()
=> Service.BuddyList.PetBuddyPresent;`
changed to
` protected static bool HasPetPresent()
=> Service.BuddyList.PetBuddy != null;`
Haven't tested this change yet
> Upgraded XIVCombo to V9

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/CustomComboPreset.cs
As mentioned in title, replaces Holy Spirit with Shield Lob when below level 64.
> PLD: Holy Spirit -> Shield Lob level sync 

- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/CustomComboPreset.cs
New Sacrificium features are an expansion to existent Lemure features under shroud after level 92.
Perfectio features are an expansion to the Communio features after level 100.
I believe this should cover most of the rest of level 91+ changes to reaper.
> RPR: Support for Sacrificium and Perfectio

- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
Here's some standard VPR combos I added. Tested locally, but it's possible I implemented some of it suboptimally
My VPR is 83 at time of PR, so I haven't tested the 90+ features
> Add standard VPR combos

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Adding more logic checks for more optimization.
> BLM: update enochian timer feature to add in insta-despair optimization

- XIVComboExpanded/Combos/GNB.cs
Not tested locally, but should work? Probably should be a feature support to get RoB up ahead of other things etc., but just wanted to add basic support since I just hit 100 GNB.
> Support Reign of Beasts

- XIVComboExpanded/Combos/AST.cs
- XIVComboExpanded/Combos/BRD.cs
- XIVComboExpanded/Combos/SCH.cs
- XIVComboExpanded/Combos/SGE.cs
- XIVComboExpanded/Combos/WHM.cs
- XIVComboExpanded/CustomComboPreset.cs
Extremely naughty features: refreshes dot for you. 
Don't wanna mess around with Eukrasian Dosis clusterfuck, maybe someone else can implement that :)
> added dot timer features for brd, ast, whm, sge, and sch

- XIVComboExpanded/Combos/ADV.cs
- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/CustomComboPreset.cs
- Implemented AttributeRework to Paladin
- Combined several ST and AoE combos.
- Split off the advanced logic on the Atonement and Divine Might features into a separate FoF optimize feature.
- Updated combos and code throughout.
> [FEATURE] Paladin Attribute Rework

- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- Updated Reaper for AttributesRework changes.
- Merged and updated several Reaper combos.
- Reordered combos to sections in UI.
- Noted all of the Shadow of Death replacement combos as very bad ideas.
> [FEATURE] Reaper Attributes Rework

- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- Updated Viper combos for the AttributesRework changes.
- Updated the descriptions of several combos, and added notes to ones that can cause sub-optimal effects.
- Updated the combo level of a number of Viper combos.
> [FEATURE] Viper Attributes Rework

- XIVComboExpanded/Combos/SGE.cs
- XIVComboExpanded/CustomComboPreset.cs
Adds an option under "Toxikon into Phlegma Feature" to also include Psyche in the combo.
> [Feature] Add Psyche into Phlegma - Toxikon combo

- XIVComboExpanded/Combos/SGE.cs
- XIVComboExpanded/CustomComboPreset.cs
Creates an option under Dosis dot feature that changes Dosis to Psyche when cooldown is available, DOT feature will still take priority.
> [Feature] SGE Dosis to Psyche when available

- XIVComboExpanded/Combos/DRK.cs
- XIVComboExpanded/CustomComboPreset.cs
+ Bugfix living shadow feature since it no longer requires 50 gauge to activate.
> DRK 2nd pass

- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- Implemented Perfect Harvest feature for Reaper, placing Perfectio on Plentiful Harvest (and Arcane Circle, with seperate enable).
- Renamed `Perfectio Feature` to `Combo Perfectio Feature`, for clarity
- Renamed several Reaper feature vars for clarity.
Fixes #352, fixes #395
> [FEATURE] Reaper - Perfect Harvest

- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/Combos/WAR.cs
- XIVComboExpanded/Interface/Changelog.cs
- Fixed WAR Surging Tempest refresh logic to properly condition the entire block on the feature.
- Fixed PLD AoE Divine Might features logic to properly handle the optimization logic and refer to the correct abilities.
> [BUGFIX] WAR and PLD

- .editorconfig
- XIVComboExpanded/Combos/PLD.cs
- XIVComboExpanded/Combos/RPR.cs
- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
- (VPR) Fixed Generation Legacy Feature when used with Steel Coil feature. Fixes #406.
- (RPR) Fixed Perfect Harvest feature when not using Arcane Harvest Feature is not enabled. Fixes #404.
- Misc spacing and formatting fixes.
> [BUGFIX] Reaper and Viper

- XIVComboExpanded/Combos/VPR.cs
- XIVComboExpanded/CustomComboPreset.cs
> Restore the glory of the VPR PvP combos

- XIVComboExpanded/Combos/GNB.cs
- XIVComboExpanded/CustomComboPreset.cs
Noticed this notable absence from the EmptyBloodfestFeature, figured it'd be worth adding
> Add the rest of the Reign combo on EmptyBloodfestFeature

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Niche high end optimization to squeeze out 84 extra potency in niche transpose lines.
> BLM: added optimization feature for umbral ice transpose lines

- XIVComboExpanded/Combos/DRK.cs
- XIVComboExpanded/CustomComboPreset.cs
> DRK: handle level 91+

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
Update eno-chan timer feature for 7.1 instant despair changes.
> BLM, 7.1 insta-despair go brrr

- XIVComboExpanded/Combos/BLM.cs
- XIVComboExpanded/CustomComboPreset.cs
I might add the standard 5+7 opener logic if anyone else still plays this job.
> Preliminary 7.2 BLM Changes

- XIVComboExpanded/Combos/AST.cs
- XIVComboExpanded/CustomComboPreset.cs
Resolves #422
I've been using these changes locally for months without issue and thought I should contribute them. As it is my first time contributing, please give extra scrutiny in case I've overlooked anything.
> AST Play to Draw separation into options for each Play type
